//Verilog testbench template generated by SCUBA Diamond (64-bit) 3.9.0.99.2
`timescale 1 ns / 1 ps
module arbiter_tb;
reg axis_aclk;

wire axis_aresetn;
wire [31:0] s0a_axis_tdata;
wire s0a_axis_tvalid;
wire s0a_axis_tready;
wire s0a_axis_tlast;
wire [31:0] s0b_axis_tdata;
wire s0b_axis_tvalid;
wire s0b_axis_tready;
wire s0b_axis_tlast;
wire [31:0] m0k_axis_tdata;
wire m0k_axis_tvalid;
wire m0k_axis_tready;
wire m0k_axis_tlast;

arbiter DUT(.*); //implicit port


always
#5.00 axis_aclk <= ~ axis_aclk;

endmodule
